baseURL = "https://elstondsouza.com.au/"
languageCode = "en-us"
title = "Elston Neil D'Souza"

theme="soho"
[params]
copyright = "Elston Neil D'Souza"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
# Color Palette https://coolors.co/0b3954-bfd7ea-ff6664-e0ff4f-fefffe
themeColor = "#0b3954"
author = "Elston D'Souza"
profilePicture = "images/profile.png"
math = true 
  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/elstonndsouza"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/elston-n-dsouza/"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/elston_neil"

  [[params.socialIcons]]
  icon = "fa-instagram"
  title = "Instagram"
  url = "https://www.instagram.com/elstonndsouza/"
	[[params.socialIcons]]
	icon = "fa-orcid"
	url = "https://orcid.org/0000-0002-5394-7260"
[menu]

  [[menu.main]]
  name = "Blog"
  weight = 100
  identifier = "posts"
  url = "/blog/"

	[[menu.main]]
  name = "Publications"
  identifier = "publications"
  weight = 300
  url = "/publications/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 300
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  identified = "contact"
  weight = 500
  url = "/contact/"
